#!/bin/sh
# qemu-pfsense
#
### BEGIN INIT INFO
# Provides:          qemu-system-x86_64
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $named autofs
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: qemu pfsense
# Description:       qemu pfsense
### END INIT INFO

case "$1" in
  start)
    exec sudo -H -u <user-id> bash -c 'qemu-system-x86_64 \
        -enable-kvm \
        -cpu host \
        -smp 4 \
        -k en-us \
        -drive id=disk,file=<path-to-image>/disk-raw,format=raw,if=none \
        -device ahci,id=ahci \
        -device ide-hd,drive=disk,bus=ahci.1 \
        -boot d \
        -device vfio-pci,host=0000:02:00.0 \
        -device vfio-pci,host=0000:03:00.0 \
        -m size=4096 \
        -nographic' &
    ;;
  stop)
    kill $(pidof qemu-system-x86_64)
    ;;

  reload|force-reload)
    ;;

  restart)
    ;;

  status)
    ;;
  *)
    echo "Usage: /etc/init.d/qemu-pfsense {start|stop|reload|force-reload|restart|status}"
    exit 1
esac

exit 0
